services:
  redis:
    container_name: "chat_app_redis"
    image: redis:latest
    networks:
      - default
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_PWD=${REDIS_PWD}
    command: ["redis-server", "--requirepass", "${REDIS_PWD}"]

networks:
  default:
